language: node_js
node_js:
- 6
branches:
  only:
  - master
  - develop
before_install:
- git checkout -qf master
before_script:
- npm run lint
before_deploy:
- git config --global user.email "potz666@gmail.com"
- git config --global user.name "eXigentCoder-CI"
- git config credential.helper "store --file=.git/credentials"
- npm version patch -m "Release %s of the library [skip ci]"
- git push https://$GH_TOKEN@github.com/eXigentCoder/krpc-node.git --all
deploy:
  skip_cleanup: true
  provider: npm
  email: potz666@gmail.com
  api_key:
    secure: lvee767Ys1p67ssChamTLbc3FM3xhHX7jpxEQdJ3wMuBY4ggffdnHiTzzNnF7OOK27raOx0hCkX9nRGnCXO2tFcfUk+bM9DhCU21HjiMlkZ8yKksfoSBZd47sCz/slpHr9vr8AeLpVEoXjZayMbssh6W+l/Nxrdh6J2Wz/HzN/Yasa/jxnueAKkewwBQtFGzk9euhPUtZMrjQHiFtLxvGKN/Oau3LXTYOuezjh9LE1KkHIn2NwMYD2UKp8IcUAOXa0bT31eSObNY7BJWzIsfZ63k5bh9Rey9M5jAtIXSCXF2NbN/kTUt0yFMeP0gROEz43PCvrcDU9BtBmLVdoLPjLgn7PbTl+5PEoXF1vcF3GlQ/HqcoZZh2yQ9cy0JUX4OEACOYKt/uKraG+yuJvy+DZF3XyVFbw+s0pBiBrhDbpZDT4Xgikb6CeQowv7yGBOXlHG6GcF4AHB6hO0DJ9mMm/z4b+jFF+PQkKP/wj6Wo1ZRpL90OpgyXVFTwvm6SKRmQzX6Wtlny0UI7ROjU+sP1lzUxCayjvp5J8uRvx9OKG+Q5zxfSqheXqka1OtmBCJE5kT+6UDhuCWxEFqLjX0x16yKBgI9ufFSTyUPulxgxKY6zsDh3CPhMNdXM6lKH7ghYqfxgNTQGco9tbFROXk1xl95AAel4/CsmSw/HYOD1c8=
  on:
    branch: master
    repo: eXigentCoder/krpc-node
env:
  global:
    secure: hgfHkLnlBZzKkkhWV020Zn8aE4x6ySnER2bh8SSScx5mFu9xyW/PjyBEx5/4HxJwQYYnQXftwo028vNZeVR3iigoCZuGjqKVVuVXX1RXxkwz1EvDG3Z5vIKzl9Wb8o7WKHBeP3f6997QWQkf5/yzT2vT1zEJJ1zX6W7Jcvb1+v+IiP8xJsP8HDY4W1gDZWj3pl6IFBm/JnMW6KoX2eyOLN8jj8j/ZF26XGOzjxNw2jS/yXgKHAv1LWe8dzWZy6bPZ8EzHC5NCACtjg0obV08X060OJ8i0ON33LwyDr3Gy0zStPIcmsl72RBrrW/+a1pK2KxFfgvMRn9SW12Ih432iX9fzCtjOf4bVCn+z+5UesmvHfxOBvsuLvd4TsP6vcuN/iqknl6u1OrrlMuBPYIwsBZCOrgbygp3PlA/M+Z/vJe54eVRPK6byyYx3560V8/MyauoHpZmXzfQiFq4y5IuwXaFJ1AjNjNEK5nfMfV+7zYWYP4JSZDSXbXPZ+sGHSgHHOpo8jBIWPXnNHE89M0RZweiRgF47fRBmQT7EBhPyL1/pKV3pF/Q1lBJxeyhueKDQBFC+bdr0kILe0bZ8MWgXYsZneQwK61Okn7LfWG5+CLwlP52NITAZn+nTKMDkxT6yn3f2/KPbz6igFFCc77CpBEDLHgWXHkOHEzWGVmBAQA=
